#spring.application.name=goshen
server:
  host: localhost
  port: 9192
#port: 8080

spring:
  datasource:
    url: jdbc:mysql://root:0000@localhost:3306/gosh_hotel_db
    username: root
    password: 0000
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect

#spring:
#  datasource:
#    username: root
#    password: 0000
#    database: gosh_hotel_db
#    url: jdbc:mysql://localhost:3306/gosh_hotel_db
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    jpa:
#      show-sql: true
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        ddl-auto: update
#        format_sql: true
#  servlet:
#      multipart:
#       max-file-size: 5MB
#       max-request-size: 5MB
#      file-size-threshold: 2KB
#

